### ISSUE TITLE
Issue to run ./ask

### ISSUE THREAD

**Issue by MasuMaru** [Bowbaq/question-generation#1]
When I run ./ask scripts/sample.txt 15
I get these errors:

Traceback (most recent call last):
  File "./ask", line 47, in <module>
    output = subprocess.check_output(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command './scripts/run.sh question-asker --debug 2>/dev/null < scripts/sample.txt' returned non-zero exit status 1

Do you have any idea how to fix this issue?

**Comment by ericalingyuan** [comment]
Hi, I have the same issue. Have you found the solutions?

**Comment by Bowbaq** [comment]
You have to run `./scripts/build.sh` first. FYI I'm not maintaining this project, this was simply a convenient location to share the code at the time.
